@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.ommina.wallpapercraftstairs.events;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;