@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.ommina.wallpapercraftstairs.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;