@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.ommina.wallpapercraftstairs.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;