@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.ommina.wallpapercraftstairs.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;